### ISSUE TITLE
Add book to library

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#10]
**Task Description**
Add book to library

**Steps**
List all steps that are required to complete the task

- Add a button that allows the user to add a book to their library
- Check if the book is already in the library
- Show the changes in the library

**Technical effort (LOE)**
Step 1: 4
Step 2: 5
Step 3: 3

**Comment by AymericBriereJAC** [comment]
Now, able to add book locally, in rough shape, but working
