### ISSUE TITLE
Browse through library

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#12]
**Task Description**
When the user clicks on the library, show a screen that shows all books

**Steps**
List all steps that are required to complete the task

- Add a library button to navigate to the library
- Show the list of books that have been added to the library

**Technical effort (LOE)**
Step 1: 3
Step 2: 4

**Comment by AymericBriereJAC** [comment]
This was implemented a while ago but never got closed
