### ISSUE TITLE
Organize the project files

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#17]
**Task Description**
Right now everything is bundled up into MainActivity,tk, moving files into an appropriate place and keeping everything organized will contribute to efficiency and productivity

**Steps**
List all steps that are required to complete the task

-  Create folder named UI for the different screens
-  Create a folder for each screen and the appropriate data associated with it 
- Test that everything still works as intended

**Technical effort (LOE)**
Medium

**Comment by AymericBriereJAC** [comment]
project reorganzied

**Comment by AymericBriereJAC** [comment]
Project is not organized using model, screen, interface etc...this leads to now having spagethi code.
