### ISSUE TITLE
Sign-Up Screen

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#3]
**Task Description**
Create a sign up screen so that the user can enter their credentials and create a new account

**Steps**
List all steps that are required to complete the task

- Add text or image informing the user that they are currently on the sign up screen
- Add a text field for the username
- Add a text field for the password
- Add a button that verifies if the credentials are valid/unique on send

**Technical effort (LOE)**
Step 1: 2
Step 2: 2
Step 3: 2
Step 4: 6

**Comment by AymericBriereJAC** [comment]
a signup and login page was added
