### ISSUE TITLE
Book Selection

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#4]
**Requirement Description**
As a user, I want to be able to click on a book in order to see its description, rating, cover, etc.

**Work breakdown structure**
A list of subtask issues links created from work breakdown structure (WBS)

### Tasks
- [x] #5 
- [x] #6 

**Effort estimation (LOE)**
10

**Comment by AymericBriereJAC** [comment]
this was finished implementing for milestone 4a
