### ISSUE TITLE
Book Description Screen

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#6]
**Task Description**
Create a screen that has details of the book that the user has selected

**Steps**
List all steps that are required to complete the task
-  Add an image of the cover of the book on the screen
- Add a description of the book
- Add other details such as the author, rating, number of pages, genre

**Technical effort (LOE)**
Step 1: 4
Step 2: 2
Step 3: 2

**Comment by AymericBriereJAC** [comment]
this got implemented at milestone 4b
