### ISSUE TITLE
Discovery screen

### ISSUE THREAD

**Issue by Carlos-LX** [Carlos-LX/5A6-group-project#8]
**Task Description**
Create a screen that showcases the different books within our catalogue

**Steps**
List all steps that are required to complete the task

- Create a composable that showcases the different books
- Create a search bar
- Add sorting options (by genre, by author)

**Technical effort (LOE)**
Step 1: 6
Step 2: 8
Step 3: 7

**Comment by AymericBriereJAC** [comment]
duplicate

**Comment by AymericBriereJAC** [comment]
this was implemented, please  add separate task for the sorting
